### ISSUE TITLE
compilation on Windows

### ISSUE THREAD

**Issue by Aroxed** [mpenkov/dtmf-cpp#2]
Hello.
Could you tell me if it is possible to compile and run this code under Windows 7? Could you suggest any tools for that?

Thanks in advance.
Andrii.

**Comment by mpenkov** [comment]
Hi,

Anything is possible, in theory :) In practice, I don't use Windows at all, so I wouldn't be able to help you much personally. Sorry!

I think if you ask someone with general C++ and Windows experience on how to build this particular project, they'll be able to help you.

Best,
Misha
